/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Avalg
 */
public class Izbornik extends javax.swing.JFrame {

    /**
     * Creates new form Izbornik
     */
    public Izbornik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBenzinskeCrpke = new javax.swing.JButton();
        btnGoriva = new javax.swing.JButton();
        lblGitHub = new javax.swing.JLabel();
        btnDjelatnici = new javax.swing.JButton();
        btnNarudzbaCisterne = new javax.swing.JButton();
        btnEraDijagram = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBenzinskeCrpke.setText("Benzinske crpke");
        btnBenzinskeCrpke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBenzinskeCrpkeActionPerformed(evt);
            }
        });

        btnGoriva.setText("Goriva");
        btnGoriva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGorivaActionPerformed(evt);
            }
        });

        lblGitHub.setText("Github");
        lblGitHub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGitHubMouseClicked(evt);
            }
        });

        btnDjelatnici.setText("Djelatnici");
        btnDjelatnici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDjelatniciActionPerformed(evt);
            }
        });

        btnNarudzbaCisterne.setText("Narudžba Cisterne");
        btnNarudzbaCisterne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNarudzbaCisterneActionPerformed(evt);
            }
        });

        btnEraDijagram.setText("ERA dijagram");
        btnEraDijagram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEraDijagramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblGitHub, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBenzinskeCrpke, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(btnGoriva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDjelatnici, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNarudzbaCisterne, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnEraDijagram, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBenzinskeCrpke)
                    .addComponent(btnDjelatnici))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGoriva)
                    .addComponent(btnNarudzbaCisterne))
                .addGap(30, 30, 30)
                .addComponent(btnEraDijagram)
                .addGap(18, 18, 18)
                .addComponent(lblGitHub)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBenzinskeCrpkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBenzinskeCrpkeActionPerformed
        new FormaBenzinskaCrpka().setVisible(true);
       

    }//GEN-LAST:event_btnBenzinskeCrpkeActionPerformed

    private void btnGorivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGorivaActionPerformed
        new FormaGorivo().setVisible(true);
    }//GEN-LAST:event_btnGorivaActionPerformed

    private void lblGitHubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGitHubMouseClicked
        try {
            Runtime.getRuntime().exec("cmd /c start https://github.com/dglavica ");
        } catch (IOException ex) {
            Logger.getLogger(Izbornik.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_lblGitHubMouseClicked

    private void btnDjelatniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDjelatniciActionPerformed
        new FormaDjelatnik().setVisible(true);
    }//GEN-LAST:event_btnDjelatniciActionPerformed

    private void btnNarudzbaCisterneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNarudzbaCisterneActionPerformed
       new FormaNarudzbaCisterne().setVisible(true);
    }//GEN-LAST:event_btnNarudzbaCisterneActionPerformed

    private void btnEraDijagramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEraDijagramActionPerformed
        new FormaERA().setVisible(true);
    }//GEN-LAST:event_btnEraDijagramActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBenzinskeCrpke;
    private javax.swing.JButton btnDjelatnici;
    private javax.swing.JButton btnEraDijagram;
    private javax.swing.JButton btnGoriva;
    private javax.swing.JButton btnNarudzbaCisterne;
    private javax.swing.JLabel lblGitHub;
    // End of variables declaration//GEN-END:variables
}
